let S={};
const money=n=>'₹'+Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
async function api(p,o){return (await fetch('/api'+p,o)).json()}
async function init(){S=await api('/state');render()}
function show(id){document.querySelectorAll('main>section').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(id==='wishlist')wishlist();if(id==='portfolio')portfolio();if(id==='orders')orders()}
function card(s){return `<div class="stock"><div class="stockTop"><b>${s.symbol}</b><span class="${s.change>=0?'gain':'loss'}">${s.change>=0?'+':''}${s.change}%</span></div><div class="company">${s.name}</div><div class="price">${money(s.price)}</div><small>${s.cap} • ${s.sector}</small><div class="actions"><button onclick="add('${s.symbol}')">♡ Wishlist</button><button onclick="trade('${s.symbol}')">Trade</button></div></div>`}
function render(){document.getElementById('balance').textContent=money(S.user.tradingBalance);document.getElementById('accountBalance').textContent=money(S.user.tradingBalance);document.getElementById('interest').innerHTML=S.stocks.slice(0,4).map(card).join('');document.getElementById('movers').innerHTML=[...S.stocks].sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,6).map(card).join('');document.getElementById('discover').innerHTML=S.stocks.slice(4).map(card).join('');activities();document.getElementById('notes').innerHTML=S.notifications.map(n=>`<p>🔔 ${n.text}</p>`).join('')}
function activities(){let v=[...S.stocks].sort((a,b)=>b.volume-a.volume),val=[...S.stocks].sort((a,b)=>b.value-a.value);document.getElementById('bought').innerHTML=rows(v,'volume');document.getElementById('volume').innerHTML=rows(v,'volume');document.getElementById('value').innerHTML=rows(val,'value')}
function rows(a,k){return a.slice(0,5).map(s=>`<div class="row"><b>${s.symbol}</b><span>${k==='volume'?s.volume.toLocaleString():money(s.value)}</span></div>`).join('')}
async function add(symbol){await api('/wishlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,folder:'My Wishlist'})});S=await api('/state');wishlist();show('wishlist')}
async function newFolder(){let name=prompt('Folder name');if(!name)return;await api('/wishlist/folder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});S=await api('/state');wishlist()}
function wishlist(){let h='';for(const [f,a] of Object.entries(S.wishlist))h+=`<div class="panel"><h3>📁 ${f} (${a.length})</h3><div class="grid">${a.map(x=>S.stocks.find(s=>s.symbol===x)).filter(Boolean).map(card).join('')}</div></div>`;document.getElementById('wishlistContent').innerHTML=h}
async function trade(symbol){let qty=Number(prompt('Quantity',1));if(!qty)return;await api('/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,qty,side:'BUY'})});S=await api('/state');render();alert('Virtual order placed')}
function portfolio(){let p=S.portfolio;for(const [id,v] of [['equity',p.equity],['mf',p.mutualFunds],['mtf',p.mtfBorrowing]])document.getElementById(id).textContent=money(v);document.getElementById('net').textContent=money(p.equity+p.mutualFunds-p.mtfBorrowing);document.getElementById('picks').innerHTML=p.investmentPicks.map(x=>`<button class="chips">${x}</button>`).join('')}
function orders(){document.getElementById('ordersList').innerHTML=S.orders.map(o=>`<div class="row"><span><b>${o.id}</b> ${o.side} ${o.qty} × ${o.symbol}</span><span>${money(o.price)} • ${o.status}</span></div>`).join('')}
function filter(t){let a=S.stocks;if(t==='gainers')a=a.filter(s=>s.change>0).sort((x,y)=>y.change-x.change);if(t==='losers')a=a.filter(s=>s.change<0).sort((x,y)=>x.change-y.change);if(t==='software')a=a.filter(s=>s.sector==='Software');if(t==='affordable')a=a.filter(s=>s.price<500);document.getElementById('discover').innerHTML=a.map(card).join('')}
function searchStocks(){let q=document.getElementById('search').value.toLowerCase();document.getElementById('discover').innerHTML=S.stocks.filter(s=>(s.symbol+s.name+s.sector).toLowerCase().includes(q)).map(card).join('')}
function downloadReport(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='stocksprint-report.json';a.click()}
init();